### ISSUE TITLE
Commitlint actions do not display error messages in the Annotation section

### ISSUE THREAD

**Issue by aj3sh** [opensource-nepal/commitlint#24]
**Describe the bug**
When the commitlint action fails, it exits without displaying the reason for the error message in the Annotation section.

**To Reproduce**
- Use the commitlint action on your CI
- Fail the commitlint with a commit message that doesn't adhere to the conventional commit message format.

**Expected behavior**
Error messages should be displayed in the Annotation section, indicating the cause of the error.

**Environment**

-   Python version: (used by commitlint action)
-   Package version: 0.2.1
-   Operating system: Github actions

**Additional context**
<img width="1074" alt="Screenshot 2024-02-08 at 9 20 00 PM" src="https://github.com/opensource-nepal/commitlint/assets/35629644/d08b64f1-251b-43ad-ac8d-26a786ce8287">

<img width="1053" alt="Screenshot 2024-02-08 at 9 30 29 PM" src="https://github.com/opensource-nepal/commitlint/assets/35629644/b2d89092-4bec-4b53-a340-2974e4d83812">

**Used yaml configuration**
```yaml
name: Commitlint

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Check commit messages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run commitlint
        uses: opensource-nepal/commitlint@v0.2.1
```
